from fastapi import FastAPI
from pydantic import BaseModel
from fastapi import Depends

from models.student import Student

from db.deps import get_db

app = FastAPI()

# always use separate schema/models for request and response
class StudentReq(BaseModel):
    name: str
    age: int
    course: str

@app.get("/")
def hello_folks():
    return {"message": "Hello, folks! from FastAPI"}

USERS = {
    "1a": {"name": "Alice", "age": 21},
    "2b": {"name": "Bob", "age": 22},
    "3a": {"name": "Charlie", "age": 23},
}    


@app.get("/user/{user_id}") # user_id is a path parameter
def get_user(user_id: str):
    user = USERS.get(user_id) # user_id is not there in USERS then this will return None
    """ USERS[user_id] -> KeyError if user_id not found"""
    if user:
        return {"user_id": user_id, "user": user}
    
    return {"message": "User not found"}

@app.get("/users") # for query params we don't have to mention anythng in endpoint declaration
def get_all_users(user_id: str = None, is_all: bool = False): # for query params we have to provide default value and the keys
    if user_id:
        user = USERS.get(user_id)
        if user:
            return {"user_id": user_id, "user": user}
        return {"message": "User not found"}
    
    # if no query or user_id then return all users
    if is_all:
        return {"users": USERS}
    
    return {"message": "No valid query parameters provided"}


@app.post("/student")
def create_student(data: StudentReq, db = Depends(get_db)):
    # object of class Student, will be a record in database table
    new_student = Student(
        name = data.name,
        age = data.age,
        course = data.course
    )
    
    db.add(new_student)
    # transform into query as
    # INSERT INTO students (name, age, course) VALUES (data.name, data.age, data.course)
    db.commit() # 
    db.refresh(new_student) # to get the autogenerated fields like id
    
    return new_student


@app.get("/students")
def get_all_students(id: int = None, db = Depends(get_db)):
    students = db.query(Student).all() # SELECT * FROM students
    if id:
        student = db.query(Student).filter(Student.id == id).first() # SELECT * FROM students WHERE id = id
        if student:
            return student
        return {"message": "Student not found"}
    return students
