from fastapi import FastAPI
from pydantic import BaseModel
from fastapi import Depends

from models.student import Student
from db.deps import get_db

app = FastAPI()

# always use separate schema/models for request and response
class StudentRequestSchema(BaseModel):
    name: str
    age: int
    course: str

class StudentUpdateSchema(BaseModel):
    name: str = None
    age: int = None
    course: str = None

@app.get("/")
def hello_folks():
    return {"message": "Hello, folks! from FastAPI for Day 2"}


@app.post("/student")
def create_student(data: StudentRequestSchema, db = Depends(get_db)):
    # object of class Student, will be a record in database table
    new_student = Student(
        name = data.name,
        age = data.age,
        course = data.course
    ) # create an object of Student class act as record or row of table on Python side
    
    db.add(new_student)
    # transform into query as
    # INSERT INTO students (name, age, course) VALUES (data.name, data.age, data.course)
    
    db.commit() # Executes the query in database which where added in session using db.add()
    db.refresh(new_student) # to get the autogenerated fields like id or To update the data on python side from database side
    
    return new_student


@app.get("/students")
def get_all_students(id: int = None, db = Depends(get_db)):
    students = db.query(Student).all() # SELECT * FROM students
    if id:
        student = db.query(Student).filter(Student.id == id).first() # SELECT * FROM students WHERE id = id
        if student:
            return student
        return {"message": "Student not found"}
    return students

@app.delete("/student")
def delete_student(id: int, db = Depends(get_db)):
    stu = db.query(Student).filter(Student.id == id).first()
    if not stu:
        return {"message": "Student not found"}
    db.delete(stu) # Deletes the record from session
    db.commit()
    return {"message": "Student deleted successfully"}

@app.put("/student/{id}")
def update_student(id: int, data: StudentRequestSchema, db = Depends(get_db)):
    stu = db.query(Student).filter(Student.id == id).first()
    if not stu:
        return {"message": "Student not found"}
    
    stu.name = data.name
    stu.age = data.age
    stu.course = data.course
    db.commit()
    db.refresh(stu) # to update the data on python side from database side
    return stu

@app.patch("/student/{id}")
def update_student_partial(id: int, data: StudentUpdateSchema, db = Depends(get_db)):
    stu = db.query(Student).filter(Student.id == id).first()
    if not stu:
        return {"message": "Student not found"}
    
    # only update the fields which are provided in request(data)
    if data.name:
        stu.name = data.name
    if data.age:
        stu.age = data.age
    if data.course:
        stu.course = data.course

    db.commit()
    db.refresh(stu) # to update the data on python side from database side
    return stu
